[package]
name = "rust_udp"
version = "0.1.0"
authors = ["Peter Lehnhardt <aliud@posteo.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
